### ISSUE TITLE
panic: inconsistent import on go 1.7

### ISSUE THREAD

**Issue by henvic** [golang/lint#231] opened 2016-08-16 23:15 UTC
After I installed go version go1.7 darwin/amd64 I started getting this issue.

I have updated with

```

go get -u github.com/golang/lint
```

and the panic still happens (just the import changed, but this is not important).

```
$ golint ./... | grep -v "^vendor" | tee /dev/stderr
panic: inconsistent import:
	func errors.New(text string) error
previously imported as:
	func errors.New(text string) error
 [recovered]
	panic: inconsistent import:
	func errors.New(text string) error
previously imported as:
	func errors.New(text string) error


goroutine 1 [running]:
panic(0x203d00, 0xc420119230)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc4204da000, 0xc4200495f0)
	/usr/local/Cellar/go/1.7/libexec/src/go/types/check.go:213 +0xae
panic(0x203d00, 0xc420119230)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:458 +0x243
golang.org/x/tools/go/gcimporter15.(*importer).declare(0xc4204da540, 0x3410e0, 0xc420239c70)
	/Users/henvic/projects/gocode/src/golang.org/x/tools/go/gcimporter15/bimport.go:184 +0x17c
golang.org/x/tools/go/gcimporter15.(*importer).obj(0xc4204da540, 0xfffffffffffffffb)
	/Users/henvic/projects/gocode/src/golang.org/x/tools/go/gcimporter15/bimport.go:212 +0x4ca
golang.org/x/tools/go/gcimporter15.BImportData(0xc420177840, 0xc4201f4d50, 0xc420169000, 0xb51, 0xe00, 0xc4203e9929, 0x6, 0x6, 0xd1a4, 0x230720, ...)
	/Users/henvic/projects/gocode/src/golang.org/x/tools/go/gcimporter15/bimport.go:97 +0x3e8
golang.org/x/tools/go/gcimporter15.Import(0xc4201f4d50, 0xc4203e9929, 0x6, 0xc4204d7280, 0xb, 0xc420438960, 0x0, 0x0)
	/Users/henvic/projects/gocode/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:178 +0x5d7
github.com/golang/lint.importer.ImportFrom(0x26c020, 0xc4201f4d50, 0xc4203e9929, 0x6, 0xc4204d7280, 0xb, 0x0, 0x229740, 0x11f6501, 0x432378)
	/Users/henvic/projects/gocode/src/github.com/golang/lint/lint16.go:16 +0x58
github.com/golang/lint.(*importer).ImportFrom(0xc420013210, 0xc4203e9929, 0x6, 0xc4204d7280, 0xb, 0x0, 0xc42025efa0, 0x0, 0x0)
	<autogenerated>:5 +0x97
go/types.(*Checker).collectObjects(0xc4204da000)
	/usr/local/Cellar/go/1.7/libexec/src/go/types/resolver.go:191 +0x826
go/types.(*Checker).checkFiles(0xc4204da000, 0xc420292480, 0x9, 0x10, 0x0, 0x0)
	/usr/local/Cellar/go/1.7/libexec/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc4204da000, 0xc420292480, 0x9, 0x10, 0xc4201f4e40, 0xc420292480)
	/usr/local/Cellar/go/1.7/libexec/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc42000f700, 0xc42028a020, 0xb, 0xc42011dc40, 0xc420292480, 0x9, 0x10, 0xc420011bd0, 0xc4200015f0, 0xc4200015c8, ...)
	/usr/local/Cellar/go/1.7/libexec/src/go/types/api.go:344 +0x1a3
github.com/golang/lint.(*pkg).typeCheck(0xc4204239f0, 0xd10000000004f610, 0x8)
	/Users/henvic/projects/gocode/src/github.com/golang/lint/lint.go:274 +0x40a
github.com/golang/lint.(*pkg).lint(0xc4204239f0, 0xc4204d9e00, 0xc42044b918, 0xc42044b910)
	/Users/henvic/projects/gocode/src/github.com/golang/lint/lint.go:130 +0x40
github.com/golang/lint.(*Linter).LintFiles(0xc420049a50, 0xc420049af0, 0xc4202b7a98, 0xc4202b7aa8, 0x3a9, 0x0, 0x0)
	/Users/henvic/projects/gocode/src/github.com/golang/lint/lint.go:110 +0x6ef
main.lintFiles(0xc4200b01b0, 0x9, 0x9)
	/Users/henvic/projects/gocode/src/github.com/golang/lint/golint/golint.go:92 +0x23c
main.lintImportedPackage(0xc4200f6a80, 0x0, 0x0)
	/Users/henvic/projects/gocode/src/github.com/golang/lint/golint/golint.go:136 +0x364
main.lintDir(0xc42025d6e0, 0xd)
	/Users/henvic/projects/gocode/src/github.com/golang/lint/golint/golint.go:107 +0x60
main.main()
	/Users/henvic/projects/gocode/src/github.com/golang/lint/golint/golint.go:49 +0x389

```

**Comment by yazgazan** [comment] 2016-08-24 07:48
Removing `$GOPATH/pkg/*` and re-installing golint worked for me.

```bash
rm -rf $GOPATH/pkg/*
go get -u github.com/golang/lint/golint
```

**Comment by henvic** [comment] 2016-08-24 23:08
Hi, @yazgazan. Have done just that and it is working again.

**Comment by dsnet** [comment] 2016-08-25 20:50
Thanks @yazgazan for helping. I'm going to close this as the issue is resolved.

**Closed by dsnet** 2016-08-25 20:50 UTC
