### ISSUE TITLE
golint panics when type-checking 

### ISSUE THREAD

**Issue by chavacava** [golang/lint#413] opened 2018-09-22 10:54 UTC
What version of Go are you using (go version)?
```
go version go1.11 linux/amd64
```

What operating system and processor architecture are you using (go env)?

```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/svc/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/svc/workspace/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build879762097=/tmp/go-build -gno-record-gcc-switches"
```

### What did you do?

I've ran 

```
golint  ./github.com/pingcap/tidb/types/field_type.go
``` 

The file is https://raw.githubusercontent.com/lamxTyler/tidb/9f4c25f222b48504503812904b73c57b153183ba/types/field_type.go

### What did you expect to see?

Standard `golint` output

### What did you see instead?

The following error trace:

```
panic: assertion failed [recovered]
        panic: assertion failed

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc000152000, 0xc000379728)
        /usr/local/go/src/go/types/check.go:236 +0x98
panic(0x618d20, 0x6a9fd0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
go/types.assert(...)
        /usr/local/go/src/go/types/errors.go:18
go/types.(*Checker).recordTypeAndValue(0xc000152000, 0x0, 0x0, 0x3, 0x6ad300, 0xc0000f31a0, 0x0, 0x0)
        /usr/local/go/src/go/types/check.go:281 +0x279
go/types.(*Checker).exprInternal(0xc000152000, 0xc00014c640, 0x6add40, 0xc0000fb000, 0x6ad300, 0xc0000f31a0, 0x40b33f)
        /usr/local/go/src/go/types/expr.go:1164 +0x17c4
go/types.(*Checker).rawExpr(0xc000152000, 0xc00014c640, 0x6add40, 0xc0000fb000, 0x6ad300, 0xc0000f31a0, 0x40bbc8)
        /usr/local/go/src/go/types/expr.go:969 +0x81
go/types.(*Checker).exprWithHint(0xc000152000, 0xc00014c640, 0x6add40, 0xc0000fb000, 0x6ad300, 0xc0000f31a0)
        /usr/local/go/src/go/types/expr.go:1597 +0x73
go/types.(*Checker).indexedElts(0xc000152000, 0xc000112c00, 0x1c, 0x20, 0x6ad300, 0xc0000f31a0, 0xffffffffffffffff, 0x6ad300)
        /usr/local/go/src/go/types/expr.go:939 +0x1e2
go/types.(*Checker).exprInternal(0xc000152000, 0xc00014c540, 0x6add40, 0xc0000fbe00, 0x0, 0x0, 0x6ad340)
        /usr/local/go/src/go/types/expr.go:1158 +0x1759
go/types.(*Checker).rawExpr(0xc000152000, 0xc00014c540, 0x6add40, 0xc0000fbe00, 0x0, 0x0, 0x0)
        /usr/local/go/src/go/types/expr.go:969 +0x81
go/types.(*Checker).multiExpr(0xc000152000, 0xc00014c540, 0x6add40, 0xc0000fbe00)
        /usr/local/go/src/go/types/expr.go:1575 +0x58
go/types.(*Checker).expr(0xc000152000, 0xc00014c540, 0x6add40, 0xc0000fbe00)
        /usr/local/go/src/go/types/expr.go:1569 +0x49
go/types.(*Checker).varDecl(0xc000152000, 0xc0000e4b40, 0xc00000d928, 0x1, 0x1, 0x0, 0x0, 0x6add40, 0xc0000fbe00)
        /usr/local/go/src/go/types/decl.go:425 +0x1b7
go/types.(*Checker).objDecl(0xc000152000, 0x6afea0, 0xc0000e4b40, 0x0, 0xc000379628, 0x0, 0x8)
        /usr/local/go/src/go/types/decl.go:244 +0x83c
go/types.(*Checker).packageObjects(0xc000152000)
        /usr/local/go/src/go/types/resolver.go:542 +0x26f
go/types.(*Checker).checkFiles(0xc000152000, 0xc00000d250, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/go/types/check.go:250 +0xa5
go/types.(*Checker).Files(0xc000152000, 0xc00000d250, 0x1, 0x1, 0xc0000df860, 0x82acb0)
        /usr/local/go/src/go/types/check.go:241 +0x49
go/types.(*Config).Check(0xc00014c240, 0xc000012490, 0x5, 0xc000056340, 0xc00000d250, 0x1, 0x1, 0xc0000df7c0, 0x4d957e, 0x0, ...)
        /usr/local/go/src/go/types/api.go:351 +0x11a
golang.org/x/lint.(*pkg).typeCheck(0xc0000ab590, 0x40bbc8, 0xd0)
        /home/svc/workspace/go/src/golang.org/x/lint/lint.go:283 +0x313
golang.org/x/lint.(*pkg).lint(0xc0000ab590, 0xc000076b70, 0x7ffc18f27e0b, 0x38)
        /home/svc/workspace/go/src/golang.org/x/lint/lint.go:153 +0x40
golang.org/x/lint.(*Linter).LintFiles(0xc000047b60, 0xc000047be8, 0x7ffc18f27e0b, 0x38, 0xc000047da0, 0x0, 0x0)
        /home/svc/workspace/go/src/golang.org/x/lint/lint.go:115 +0x634
main.lintFiles(0xc00004c4e0, 0x1, 0x1)
        /home/svc/workspace/go/src/golang.org/x/lint/golint/golint.go:114 +0x1bd
main.main()
        /home/svc/workspace/go/src/golang.org/x/lint/golint/golint.go:78
```

### Remarks

1) I was unable to reproduce the problem with go 1.10
2) The panic is thrown when checking `fieldTypeMergeRules` at line 484 of the file.

**Comment by griesemer** [comment] 2018-09-22 19:29
I believe this is a duplicate of https://github.com/golang/lint/issues/411 (golang equivalent https://github.com/golang/go/issues/27346), which was fixed by https://go-review.googlesource.com/c/go/+/132355 .

Using the latest code of x/tools, x/lint, and the std library, I cannot reproduce this. Closing.

**Closed by griesemer** 2018-09-22 19:29 UTC

**Comment by griesemer** [comment] 2018-09-22 19:30
PS: Undoing the fix in https://go-review.googlesource.com/c/go/+/132355 causes this bug to appear again, so I'm confident this is the same (now fixed) issue.
