### ISSUE TITLE
Golint should ignore files with `DO NOT EDIT` in comments

### ISSUE THREAD

**Issue by ng-vu** [golang/lint#268] opened 2017-01-12 10:42 UTC
I sometimes ran into `golint` errors on generated files and have to manually ignore those files from CI scripts.

Generated files often have `DO NOT EDIT` in comments. So I suggest to make `golint` smarter by ignoring files which have `DO NOT EDIT` in comments.

**Comment by dsnet** [comment] 2017-01-12 16:36
Closing as duplicate of #239.

**Closed by dsnet** 2017-01-12 16:36 UTC
