### ISSUE TITLE
parsing go.mod: unexpected module path "golang.org/x/lint"

### ISSUE THREAD

**Issue by psampaz** [golang/lint#446] opened 2019-04-02 15:07 UTC
When i run 

```
go get -u 
```

I get the following error:

```
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
```

My go.mod file is the following:

```
module mymodule

go 1.12

require (
	github.com/aws/aws-sdk-go v1.18.5
	github.com/cespare/xxhash v1.1.0 // indirect
	github.com/coocood/freecache v1.1.0
	github.com/gemnasium/logrus-graylog-hook/v3 v3.0.2
	github.com/kr/pretty v0.1.0 // indirect
	github.com/pkg/errors v0.8.1
	github.com/sirupsen/logrus v1.4.0
	github.com/spf13/viper v1.3.2
	github.com/streadway/amqp v0.0.0-20190312223743-14f78b41ce6d
	github.com/uber-go/atomic v1.3.2 // indirect
	go.etcd.io/bbolt v1.3.2
	go.uber.org/atomic v1.3.2 // indirect
	go.uber.org/ratelimit v0.0.0-20180316092928-c15da0234277
	golang.org/x/crypto v0.0.0-20190313024323-a1f597ede03a
	golang.org/x/net v0.0.0-20190318221613-d196dffd7c2b
	golang.org/x/oauth2 v0.0.0-20190319182350-c85d3e98c914
	golang.org/x/sync v0.0.0-20190227155943-e225da77a7e6
	google.golang.org/api v0.2.0
)
```

My Go version is:

```
go version go1.12.1 linux/amd64
```

the output of go get -u is the following

```
go: finding github.com/alecthomas/template latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding golang.org/x/net latest
go: finding gopkg.in/check.v1 latest
go: finding golang.org/x/crypto latest
go: finding github.com/prometheus/client_model latest
go: finding golang.org/x/exp latest
go: finding golang.org/x/sync latest
go: finding github.com/armon/consul-api latest
go: finding go.uber.org/ratelimit latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/oauth2 latest
go: finding github.com/kr/logfmt latest
go: finding golang.org/x/tools latest
go: finding github.com/beorn7/perks latest
go: finding github.com/BurntSushi/xgb latest
go: finding github.com/prometheus/procfs latest
go: finding golang.org/x/image latest
go: finding golang.org/x/sys latest
go: finding github.com/streadway/amqp latest
go: finding golang.org/x/lint latest
go: finding github.com/jmespath/go-jmespath latest
go: finding honnef.co/go/tools latest
go: finding github.com/ugorji/go/codec latest
go: finding golang.org/x/time latest
go: finding github.com/alecthomas/units latest
go: finding golang.org/x/build latest
go: finding github.com/jellevandenhooff/dkim latest
go: finding github.com/eapache/go-xerial-snappy latest
go: finding github.com/flynn/go-shlex latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding github.com/anmitsu/go-shlex latest
go: finding github.com/bradfitz/go-smtpd latest
go: finding github.com/google/pprof latest
go: finding gopkg.in/tomb.v1 latest
go: finding github.com/golang/glog latest
go: finding github.com/rcrowley/go-metrics latest
go: finding github.com/tarm/serial latest
go: finding github.com/golang/lint latest
go: finding github.com/gregjones/httpcache latest
go: finding golang.org/x/mobile latest
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding grpc.go4.org latest
go: finding github.com/coreos/go-systemd latest
go: finding go4.org latest
go get: error loading module requirements
```

**Comment by frieser** [comment] 2019-04-03 11:01
Same error

**Comment by alexandrevilain** [comment] 2019-04-03 12:22
Same error too!
```
go version go1.12 linux/amd64
```

**Comment by grempe** [comment] 2019-04-03 18:54
I am also seeing this issue when using `go get -u` for the dependency I'm trying to update. If I remove the `-u` it works. Perhaps this issue has come alive again since re-adding the `go.mod` file?

https://github.com/golang/lint/issues/436

```
...
get "go4.org": found meta tag get.metaImport{Prefix:"go4.org", VCS:"git", RepoRoot:"https://github.com/go4org/go4"} at https://go4.org?go-get=1
go: finding github.com/golang/lint latest
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding go4.org latest
go get: error loading module requirements
```

**Comment by psampaz** [comment] 2019-04-06 17:18
related issue on main Go repo https://github.com/golang/go/issues/30831

**Comment by matthijskooijman** [comment] 2019-04-15 12:44
Also see https://github.com/golang/go/issues/30833 and https://github.com/golang/lint/issues/436

**Comment by matthijskooijman** [comment] 2019-04-16 12:27
The problem is that some package in your dependency graph is still referencing github.com/golang/lint, rather than golang.org/x/lint. Due to https://github.com/golang/go/issues/30833 this problem surfaces even when an *older* version of a module has the incorrect reference. That is, even if the package directly depending lint is fixed, as long as some other package depends on an older version of that directly depending package, this problem will still trigger. To fix this, you will have to make sure that all incorrect references are gone from your module graph (which likely requires updating one or more modules on the dependency path from your project to lint and them manually upgrading the first modules on that path).

See https://github.com/sourcegraph/go-diff/issues/34 for some discussion of essentially the same issue in go-diff, along with some suggestions to use `gotip` for a more useful error message.

As a workaround, I think you can use a replace directive to point to the right repo:

    go mod edit -replace github.com/golang/lint=golang.org/x/lint@latest

Note that this adds a line to `go.mod`, but the `latest` here is replaced by an actual version number when the `go.mod` is rewritten (so you might need to update that later).

This bug is indeed triggered by re-adding the `go.mod` file, since that causes a problem when the import path inside the `go.mod` file does not match the import path used in the depending module.

**Comment by matthijskooijman** [comment] 2019-04-16 12:36
@psampaz, I just tested with your `go.mod` file and can reproduce your problem. Using gotip, I get:

```
$ gotip get -u -m
[ snip output]
go get: go.opencensus.io@v0.19.1 ->
        google.golang.org/genproto@v0.0.0-20181219182458-5a97ab628bfb ->
        google.golang.org/grpc@v1.16.0 ->
        github.com/golang/lint@v0.0.0-20180702182130-06c8688daad7 ->
        github.com/golang/lint@v0.0.0-20190409202823-959b441ac422: parsing go.mod: unexpected module path "golang.org/x/lint"
```

This shows the path of modules that pull in the faulty lint. I know that grpc has a fixed version, I can see that https://github.com/google/go-genproto/blob/master/go.mod has a fixed version, so that leaves only opencensus. I couldn't find any sources, but I just tried upgrading it manually, which seems to work. That is, running `go get -u -m go.opencensus.io` followed by `go get -u -m` completes successfully. Note that the `-m` is optional, AFAIU it just prevents actually installing stuff into your $GOPATH (for non-module-enabled code to use) and only updates it in your go.mod and downloads it for module-enable code to use.

**Comment by psampaz** [comment] 2019-04-16 14:59
thank you @matthijskooijman for your explanatory comments. They were really helpful. 

I hope this gets fixed properly on the next version of Go.

**Comment by matthijskooijman** [comment] 2019-04-24 07:11
For anyone looking to solve this problem, @jadekler has written (somewhat extensively) about this issue and how to fix it at https://golang/go/wiki/Resolving-Problems-From-Modified-Module-Path.

**Comment by rdhariwal** [comment] 2019-04-26 18:54
> For anyone looking to solve this problem, @jadekler has written (somewhat extensively) about this issue and how to fix it at https://golang/go/wiki/Resolving-Problems-From-Modified-Module-Path.

https://golang/go/wiki/Resolving-Problems-From-Modified-Module-Path
@matthijskooijman link is broken for me

**Comment by matthijskooijman** [comment] 2019-04-26 19:15
W00ps, fixed the link. Copied it from a place where github had hidden the github.com part :-)

**Closed** 2021-05-08 21:24 UTC
