### ISSUE TITLE
ID is not necessarily an abbreviation / Freudian code

### ISSUE THREAD

**Issue by greendrake** [golang/lint#323] opened 2017-08-30 23:20 UTC
The linter currently requires variables like `GatewayId` to be named `GatewayID` because of [this](https://github.com/golang/lint/blob/master/lint.go#L754).

The thing is, "Id" in cases like the above is not an initialism/abbreviation/acronym. It is just a _shortening_ from "identifier" or "identification" — not "identity document" or any other two-word term.

I therefore suggest removing `ID` from that map, because requiring to rename `GatewayId` to `GatewayID` does not make any sense.

**Comment by dominikh** [comment] 2017-08-30 23:50
Duplicate of #89.

**Comment by andybons** [comment] 2018-01-05 18:06
Closing due to it being a duplicate.

**Closed by andybons** 2018-01-05 18:06 UTC

**Comment by berlincount** [comment] 2019-10-09 10:54
I disagree with this issue being truly closed.
